foo = [uint, text, bytes]

bar = {
	foo: #6.13(foo),
	? derp: uint,
	1 : uint / null,
	? 5: text,
	five: 5,
}

table_arr_members = {
	arr: [*u32],
	arr2: [*foo],
	table: { * uint => text },
}

data = { * #6.14(bytes) => { * uint => { * #6.9(uint) => [* #6.18([* text]) ] } } }

deeply_nested = [ data: data ]