import type { RoadmapIssue } from "./errors.ts";
import type { SpanId } from "./model/core.ts";
import type {
  ManifestEntry,
  RoadmapDocument,
  SourceReplacement,
  SourceSpan,
} from "./model/documents.ts";
import {
  ExpectedByteViewError,
  exactProjectedFieldSegment,
  type CompletedRenderIr,
  type RenderChunk,
} from "./render_ir.ts";

export interface SpanValidationInput {
  readonly document: RoadmapDocument;
  readonly completed: CompletedRenderIr;
}

const codePointSort = (left: string, right: string): number =>
  left < right ? -1 : left > right ? 1 : 0;

function issue(
  document: RoadmapDocument,
  code: Extract<RoadmapIssue["code"], `E-SPAN-${string}`> | "E-SOURCE-DIGEST",
  logical_path: string,
  message: string,
  span?: { start_byte: number; end_byte: number },
): RoadmapIssue {
  return {
    code,
    source: document.document.source_path,
    logical_path,
    ...(span === undefined ? {} : { span }),
    message,
    exit: 1,
  };
}

function ownerKey(kind: ManifestEntry["kind"], id: string): string {
  return JSON.stringify([kind, id]);
}

function replacementMap(document: RoadmapDocument): ReadonlyMap<string, readonly SourceReplacement[]> {
  const result = new Map<string, SourceReplacement[]>();
  if (document.document.schema_version === 0) return result;
  const add = (kind: ManifestEntry["kind"], id: string, value: object): void => {
    if (!("source_replacements" in value) || !Array.isArray(value.source_replacements)) return;
    for (const replacement of value.source_replacements as SourceReplacement[]) {
      const key = JSON.stringify([kind, id, replacement.span_id]);
      const rows = result.get(key) ?? [];
      rows.push(replacement);
      result.set(key, rows);
    }
  };
  for (const value of document.sections) add("section", value.section_id, value);
  for (const value of document.fragments) add("fragment", value.fragment_id, value);
  for (const value of document.legacy_markers) add("legacy_marker", value.marker_id, value);
  for (const value of document.records) add("record", value.id, value);
  for (const value of document.parts) add("part", value.part_id, value);
  return result;
}

function expectedStatus(chunk: RenderChunk): SourceSpan["migration_status"] {
  if (chunk.owner.kind === "generated_slot") return "generated";
  return chunk.owner.field === "source_block_md" ? "raw" : "replaced";
}

function chunkSpanOwners(chunks: readonly RenderChunk[]): Map<SpanId, RenderChunk[]> {
  const result = new Map<SpanId, RenderChunk[]>();
  for (const chunk of chunks) {
    for (const spanId of chunk.source_span_ids) {
      const owners = result.get(spanId) ?? [];
      owners.push(chunk);
      result.set(spanId, owners);
    }
  }
  return result;
}

type ProjectedOwnerKind = Exclude<ManifestEntry["kind"], "generated_slot">;

interface SemanticSpanOwner {
  readonly kind: ProjectedOwnerKind;
  readonly id: string;
  readonly expected_field?: "body_md" | "marker_md";
  readonly projection_visibility: "document" | "semantic_only";
  readonly source_replacements: readonly SourceReplacement[];
}

function semanticSpanOwners(document: RoadmapDocument): readonly SemanticSpanOwner[] {
  if (document.document.schema_version !== 1) return [];
  const result: SemanticSpanOwner[] = [];
  for (const value of document.sections) {
    if ("render_authority" in value && value.render_authority === "semantic") result.push({
      kind: "section", id: value.section_id, expected_field: "body_md",
      projection_visibility: "document", source_replacements: value.source_replacements,
    });
  }
  for (const value of document.fragments) {
    if ("render_authority" in value && value.render_authority === "semantic") result.push({
      kind: "fragment", id: value.fragment_id, expected_field: "body_md",
      projection_visibility: "document", source_replacements: value.source_replacements,
    });
  }
  for (const value of document.legacy_markers) {
    if ("render_authority" in value && value.render_authority === "semantic") result.push({
      kind: "legacy_marker", id: value.marker_id, expected_field: "marker_md",
      projection_visibility: "document", source_replacements: value.source_replacements,
    });
  }
  for (const value of document.records) {
    if ("render_authority" in value && value.render_authority === "semantic") result.push({
      kind: "record", id: value.id, projection_visibility: value.projection_visibility,
      source_replacements: value.source_replacements,
    });
  }
  for (const value of document.parts) {
    if ("render_authority" in value && value.render_authority === "semantic") result.push({
      kind: "part", id: value.part_id, expected_field: "body_md",
      projection_visibility: "document", source_replacements: value.source_replacements,
    });
  }
  return Object.freeze(result);
}

/**
 * Validate complete half-open source accounting against completed generated bytes only. The view
 * owns its private chunk snapshots; this seam has no committed-projection read or materialization.
 */
export function validateSourceSpans(input: SpanValidationInput): readonly RoadmapIssue[] {
  const { document, completed } = input;
  const sourceFacts = completed.expected_bytes.sourceFacts();
  const issues: RoadmapIssue[] = [];
  for (const owner of semanticSpanOwners(document)) {
    const ownerPath = `${owner.kind}[${JSON.stringify(owner.id)}]`;
    if (owner.projection_visibility === "document" && owner.source_replacements.length === 0) {
      issues.push(issue(document, "E-SPAN-OWNER", `${ownerPath}.source_replacements`, "document-visible semantic owner requires replacement spans"));
    }
    if (owner.projection_visibility === "semantic_only" && owner.source_replacements.length !== 0) {
      issues.push(issue(document, "E-SPAN-OWNER", `${ownerPath}.source_replacements`, "semantic-only record forbids replacement spans"));
    }
    if (owner.projection_visibility === "document") {
      if (owner.expected_field !== undefined && (
        owner.source_replacements.length !== 1 ||
        owner.source_replacements[0]?.replacement_field !== owner.expected_field
      )) {
        issues.push(issue(
          document,
          "E-SPAN-OWNER",
          `${ownerPath}.source_replacements`,
          `semantic structural owner requires exactly one ${owner.expected_field} replacement`,
        ));
      }
      const fields = new Set<string>();
      const spanIds = new Set<string>();
      for (const replacement of owner.source_replacements) {
        if (fields.has(replacement.replacement_field)) {
          issues.push(issue(
            document,
            "E-SPAN-OWNER",
            `${ownerPath}.source_replacements`,
            `replacement field ${JSON.stringify(replacement.replacement_field)} is duplicated`,
          ));
        }
        if (spanIds.has(replacement.span_id)) {
          issues.push(issue(
            document,
            "E-SPAN-OWNER",
            `${ownerPath}.source_replacements`,
            `replacement span ID ${JSON.stringify(replacement.span_id)} is duplicated`,
          ));
        }
        fields.add(replacement.replacement_field);
        spanIds.add(replacement.span_id);
        const segments = completed.projected_field_segments.filter((segment) =>
          segment.owner_kind === owner.kind && segment.owner_id === owner.id &&
          segment.logical_path === replacement.replacement_field
        );
        const declaredSpans = document.spans.filter((span) =>
          span.id === replacement.span_id && span.source_kind === owner.kind && span.owner_id === owner.id
        );
        if (segments.length !== 1 || declaredSpans.length !== 1) {
          issues.push(issue(
            document,
            "E-SPAN-OWNER",
            `${ownerPath}.source_replacements`,
            `replacement ${JSON.stringify(replacement.span_id)} has ${segments.length} projected segments and ${declaredSpans.length} source spans, expected exactly one of each`,
          ));
        }
      }
      const ownerSegments = completed.projected_field_segments.filter((segment) =>
        segment.owner_kind === owner.kind && segment.owner_id === owner.id
      );
      for (const segment of ownerSegments) {
        const count = owner.source_replacements.filter((replacement) =>
          replacement.replacement_field === segment.logical_path
        ).length;
        if (count !== 1) {
          issues.push(issue(
            document,
            "E-SPAN-OWNER",
            `${ownerPath}.projected_field_segments`,
            `projected field ${JSON.stringify(segment.logical_path)} has ${count} replacements, expected exactly one`,
          ));
        }
      }
    }
    if (owner.projection_visibility !== "semantic_only") continue;
    for (const span of document.spans.filter((candidate) =>
      candidate.source_kind === owner.kind && candidate.owner_id === owner.id
    )) {
      issues.push(issue(document, "E-SPAN-OWNER", `source_span[${JSON.stringify(span.id)}]`, "semantic-only record forbids source spans", {
        start_byte: span.start_byte,
        end_byte: span.end_byte,
      }));
    }
  }
  const spans = [...document.spans].sort((left, right) =>
    left.start_byte - right.start_byte || codePointSort(left.id, right.id)
  );
  if (spans.length === 0) {
    issues.push(issue(document, "E-SPAN-EMPTY", "source_span", "source span ledger is empty"));
    return Object.freeze(issues);
  }

  if (sourceFacts.byte_length !== document.document.frozen_source_byte_length) {
    issues.push(issue(
      document,
      "E-SPAN-COVERAGE",
      "document.frozen_source_byte_length",
      `expected chunks have ${sourceFacts.byte_length} bytes, expected ${document.document.frozen_source_byte_length}`,
    ));
  }
  if (sourceFacts.sha256 !== document.document.frozen_source_sha256) {
    issues.push(issue(
      document,
      "E-SOURCE-DIGEST",
      "document.frozen_source_sha256",
      `expected-chunk digest ${sourceFacts.sha256} does not match ${document.document.frozen_source_sha256}`,
    ));
  }
  if (sourceFacts.line_count !== document.document.frozen_source_line_count) {
    issues.push(issue(
      document,
      "E-SPAN-COVERAGE",
      "document.frozen_source_line_count",
      `expected chunks have ${sourceFacts.line_count} lines, expected ${document.document.frozen_source_line_count}`,
    ));
  }
  if (sourceFacts.eof !== document.document.frozen_source_eof) {
    issues.push(issue(
      document,
      "E-SPAN-COVERAGE",
      "document.frozen_source_eof",
      `expected chunks have ${sourceFacts.eof} EOF, expected ${document.document.frozen_source_eof}`,
    ));
  }

  const ownersBySpan = chunkSpanOwners(completed.chunks);
  const replacements = replacementMap(document);
  const declaredSpanIds = new Set(document.spans.map((span) => span.id));
  for (const [spanId, owners] of ownersBySpan) {
    if (!declaredSpanIds.has(spanId)) {
      issues.push(issue(
        document,
        "E-SPAN-OWNER",
        `render.source_span_ids[${JSON.stringify(spanId)}]`,
        `chunk refers to undeclared span from ${owners.length} owner(s)`,
      ));
    }
  }

  let previousEnd = 0;
  const seenSpanIds = new Set<SpanId>();
  for (const [sortedIndex, span] of spans.entries()) {
    const logicalPath = `source_span[${JSON.stringify(span.id)}]`;
    const coordinate = { start_byte: span.start_byte, end_byte: span.end_byte };
    if (seenSpanIds.has(span.id)) {
      issues.push(issue(document, "E-SPAN-OWNER", logicalPath, "span ID is duplicated", coordinate));
    }
    seenSpanIds.add(span.id);
    if (
      !Number.isSafeInteger(span.start_byte) || !Number.isSafeInteger(span.end_byte) ||
      span.start_byte < 0 || span.end_byte < 0 || span.start_byte >= span.end_byte ||
      span.end_byte > sourceFacts.byte_length
    ) {
      issues.push(issue(
        document,
        "E-SPAN-BOUNDS",
        logicalPath,
        `invalid half-open span [${span.start_byte}, ${span.end_byte})`,
        coordinate,
      ));
      continue;
    }
    if (sortedIndex === 0 && span.start_byte !== 0) {
      issues.push(issue(
        document,
        "E-SPAN-GAP",
        logicalPath,
        `first span starts at ${span.start_byte}, expected 0`,
        coordinate,
      ));
    } else if (span.start_byte > previousEnd) {
      issues.push(issue(
        document,
        "E-SPAN-GAP",
        logicalPath,
        `gap [${previousEnd}, ${span.start_byte}) is unowned`,
        coordinate,
      ));
    } else if (span.start_byte < previousEnd) {
      issues.push(issue(
        document,
        "E-SPAN-OVERLAP",
        logicalPath,
        `span starts at ${span.start_byte} before prior end ${previousEnd}`,
        coordinate,
      ));
    }
    previousEnd = Math.max(previousEnd, span.end_byte);

    let expectedSlice;
    try {
      expectedSlice = completed.expected_bytes.slice(span.start_byte, span.end_byte);
    } catch (error) {
      issues.push(issue(
        document,
        error instanceof ExpectedByteViewError && error.reason === "utf8-boundary"
          ? "E-SPAN-UTF8-BOUNDARY"
          : "E-SPAN-BOUNDS",
        logicalPath,
        error instanceof Error ? error.message : String(error),
        coordinate,
      ));
      continue;
    }
    const expectedDigest = completed.expected_bytes.sha256(expectedSlice);
    if (span.sha256 !== expectedDigest) {
      issues.push(issue(
        document,
        "E-SPAN-DIGEST",
        logicalPath,
        `span digest ${span.sha256} does not match expected-chunk digest ${expectedDigest}`,
        coordinate,
      ));
    }

    const owners = ownersBySpan.get(span.id) ?? [];
    if (owners.length !== 1) {
      issues.push(issue(
        document,
        "E-SPAN-OWNER",
        logicalPath,
        `span has ${owners.length} render owners, expected exactly one`,
        coordinate,
      ));
      continue;
    }
    const chunk = owners[0];
    if (chunk.owner.kind !== span.source_kind) {
      issues.push(issue(
        document,
        "E-SPAN-KIND",
        logicalPath,
        `span kind ${span.source_kind} does not match render owner kind ${chunk.owner.kind}`,
        coordinate,
      ));
    }
    if (chunk.owner.id !== span.owner_id) {
      issues.push(issue(
        document,
        "E-SPAN-OWNER",
        logicalPath,
        `span owner ${JSON.stringify(span.owner_id)} does not match ${JSON.stringify(chunk.owner.id)}`,
        coordinate,
      ));
    }
    const status = expectedStatus(chunk);
    if (span.migration_status !== status) {
      issues.push(issue(
        document,
        "E-SPAN-STATUS",
        logicalPath,
        `span status ${span.migration_status} does not match render authority ${status}`,
        coordinate,
      ));
    }
    if (status === "raw" && span.owner_field !== chunk.owner.field) {
      issues.push(issue(
        document,
        "E-SPAN-OWNER",
        logicalPath,
        `raw span field ${span.owner_field} does not match ${chunk.owner.field}`,
        coordinate,
      ));
    } else if (status === "generated" && span.owner_field !== "generated") {
      issues.push(issue(
        document,
        "E-SPAN-OWNER",
        logicalPath,
        "generated span owner_field must be generated",
        coordinate,
      ));
    } else if (status === "replaced") {
      const replacementRows = replacements.get(JSON.stringify([
        chunk.owner.kind,
        chunk.owner.id,
        span.id,
      ])) ?? [];
      const replacement = replacementRows[0];
      const projectedKind = chunk.owner.kind === "generated_slot" ? undefined : chunk.owner.kind;
      const segment = replacement === undefined || projectedKind === undefined
        ? undefined
        : exactProjectedFieldSegment(
          completed,
          chunk,
          projectedKind,
          chunk.owner.id,
          replacement.replacement_field,
          span.start_byte,
          span.end_byte,
        );
      if (
        replacementRows.length !== 1 || replacement === undefined ||
        replacement.replacement_field !== span.owner_field ||
        !chunk.consumed_fields.includes(span.owner_field) || segment === undefined
      ) {
        issues.push(issue(
          document,
          "E-SPAN-OWNER",
          logicalPath,
          `replaced span field ${JSON.stringify(span.owner_field)} is not bijectively bound to its complete exact projected field segment`,
          coordinate,
        ));
      }
    }
  }

  const expectedEnd = document.document.frozen_source_byte_length;
  if (previousEnd !== expectedEnd || previousEnd !== completed.expected_bytes.byte_length) {
    issues.push(issue(
      document,
      "E-SPAN-COVERAGE",
      "source_span",
      `span coverage ends at ${previousEnd}; frozen/expected ends are ${expectedEnd}/${completed.expected_bytes.byte_length}`,
    ));
  }
  return Object.freeze(issues);
}
