//! The emitted `no-std-check/` shim crate: a tiny `#![no_std]` crate that depends on the generated
//! rust crate with `default-features = false`, so a consumer can prove in one command that the crate
//! still builds without `std`.
//!
//! # Why the tool emits it at all
//!
//! The generated subtree (`src/generated/**`) is held `no_std`-clean by this repo's own gates. The
//! crate root `src/lib.rs` is seeded once and then owned by the consumer, so hand-added utils are the
//! one thing that can break `no_std` for a generated crate — and detecting that is not something the
//! generator can do from here. The shim converts it into a check the consumer runs, and the seeded
//! root's header comment points at it (`export::SEEDED_RUST_CRATE_ROOT`).
//!
//! # What it opts out of
//!
//! Everything per-crate. The shim is NOT a fourth generated crate: no seed-once root, no manifest
//! changeset, no comment/code-preservation overlay, no extern-interface export, no `--config`
//! sidecars. Both files are built from `Cli` alone and the whole directory is delete-and-recreated
//! every run (see [`super::export`]'s emission site), which is why its `Cargo.toml` is a hand-built
//! string rather than a `cargo_manifest` op set — nothing in it is co-owned, so there is nothing to
//! merge.

use crate::cli::Cli;
use std::collections::BTreeMap;

/// The shim's directory, a sibling of `rust/`/`wasm/` under `--output` and outside the
/// `--package-json` nesting (the shim reaches the crate it checks by a computed relative path rather
/// than moving with it).
///
/// A constant rather than a literal at one site because two files spell it: this module keys its
/// output with it, and `export()` clobbers the directory by it. It stays HERE rather than in
/// `generation::layout` because both readers are inside the emitter — `layout` owns only the facts
/// something outside `generation/` reads back, and says so.
pub(crate) const NO_STD_CHECK_DIR: &str = "no-std-check";

/// The shim's cargo package name suffix: `--lib-name` plus this. It exists so a `--config`
/// multi-crate tree, whose crates have distinct lib names, gets distinct shim package names.
pub(crate) const NO_STD_CHECK_PACKAGE_SUFFIX: &str = "-no-std-check";

/// The documented one-liner, verbatim. LOCKSTEP: the same command text appears in the seeded rust
/// crate root (`export::SEEDED_RUST_CRATE_ROOT`, hence in every blessed corpus snapshot of it) and in
/// `docs/docs/output_format.mdx`. A consumer reads the seeded root, copies the line, and runs it
/// against the file this module writes — so the three spellings must stay byte-identical.
const CHECK_COMMAND: &str = "cargo check --manifest-path <output-root>/no-std-check/Cargo.toml \
                             --target thumbv7m-none-eabi";

/// The two files of the shim crate, keyed by path RELATIVE TO THE OUTPUT ROOT (`no-std-check/…`) —
/// the same keying `extern_interface_files` uses, and the reason both land as top-level siblings of
/// `rust/` rather than inside it.
///
/// A pure function of `Cli`: it needs no IR at all, because nothing about the shim depends on what
/// the spec declares. That is deliberate — the shim asserts a property of the CRATE, and a spec-shaped
/// shim would make the check's meaning vary by input.
pub(crate) fn no_std_check_files(cli: &Cli) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    files.insert(format!("{NO_STD_CHECK_DIR}/Cargo.toml"), cargo_toml(cli));
    files.insert(format!("{NO_STD_CHECK_DIR}/src/lib.rs"), lib_rs(cli));
    files
}

/// The relative path from `<output>/no-std-check/` to the generated rust crate.
///
/// LOCKSTEP: this is the third reader of the `--package-json` nesting rule, whose other two are
/// `GenerationScope::export`'s `rust_dir` (where the one-level-down decision is actually made) and
/// `config::crate_relative` (which restates it for a crate reading ANOTHER crate's output). The shim
/// does NOT move with the crates — it stays at the output root — so it absorbs the nesting into its
/// dep path instead. Change all three together.
fn dep_path(cli: &Cli) -> &'static str {
    if cli.package_json {
        "../rust/rust"
    } else {
        "../rust"
    }
}

fn cargo_toml(cli: &Cli) -> String {
    let lib_name = &cli.lib_name;
    format!(
        "\
# Generated by cddl-codegen. This whole directory is tool-owned and is DELETED AND REWRITTEN on
# every regeneration — edits here do not survive, and nothing in it is merged with a previous run.
#
# What it is for: proving the generated crate still compiles without `std`. Everything under
# `src/generated/**` is held no_std-clean by the generator; hand-written code added to the generated
# crate's own `src/lib.rs` is the part nobody but you can check. Run:
#
#   {CHECK_COMMAND}
#
# A failure here with an otherwise unmodified generated crate is caused by hand-written additions.

[package]
name = \"{lib_name}{NO_STD_CHECK_PACKAGE_SUFFIX}\"
version = \"0.0.0\"
edition = \"2024\"
publish = false

[dependencies]
{lib_name} = {{ path = \"{dep_path}\", default-features = false }}

# Deliberately standalone. Cargo unifies features across a whole dependency graph, so if this crate
# were a member of the surrounding workspace, ANY other member turning `std` back on for a shared
# dependency would silently satisfy this check while the crate is not in fact no_std-clean. An empty
# `[workspace]` table also means adding this directory can never disturb a workspace that does not
# list it.
[workspace]
",
        dep_path = dep_path(cli),
    )
}

fn lib_rs(cli: &Cli) -> String {
    // Under `--common-import-override` the runtime modules (`error`, `ordered_hash_map`, …) are not
    // emitted at all — the override crate owns them — so there is no generated type here to name.
    // The fallback names the crate itself, which still forces its whole `no_std` build.
    let lib_name_code = cli.lib_name_code();
    let body = if cli.export_static_files() {
        format!(
            "\
// Asserts more than \"the crate builds\": naming a generated type through the dependency's crate root
// also proves that root still re-exports `generated::*`, which is what hand edits to it can break.
pub type _NoStdCheckDeserializeError = {lib_name_code}::error::DeserializeError;
"
        )
    } else {
        format!(
            "\
// This crate was generated with `--common-import-override`, so it owns no runtime modules to name a
// type from; depending on it is what forces its whole `no_std` build. NOTE: such a crate also needs
// the override crate added to its `[dependencies]` by hand before any check here can pass.
use {lib_name_code} as _;
"
        )
    };
    format!(
        "\
//! Generated by cddl-codegen. This crate is tool-owned and is DELETED AND REWRITTEN on every
//! regeneration — do not edit it.
//!
//! It depends on the generated crate with `default-features = false`, so a green check here means
//! that crate builds with no `std`. Host targets always link `std`, so the check needs a no-std
//! target:
//!
//!   {CHECK_COMMAND}
//!
//! A failure here with an otherwise unmodified generated crate is caused by hand-written additions.

#![no_std]

{body}"
    )
}
