foo = #6.11([uint, text, bytes]) ; @used_as_key

bar = {
	foo: #6.13(foo),
	? derp: uint,
	1 : uint / null,
	? 5: text,
	five: 5,
}

table = { * uint => text }

u32 = uint .size 4 ; 4 bytes

table_arr_members = {
	arr: [*u32],
	arr2: [*foo],
	table: table,
}

data = { * #6.14(bytes) => { * uint => { * #6.9(uint) => [* #6.18([* text]) ] } } }

deeply_nested = [ data: data ]

string64 = text .size (0..64)

tagged_text = #6.9(text)

string_16_32 = #6.7(text .size (16..32))

type_choice = 0 / "hello world" / uint / text / #6.16([*uint])

non_overlapping_type_choice_all = uint / nint / text / bytes / #6.13("hello world") / [* uint] / { *text => uint }

non_overlapping_type_choice_some = uint / nint / text ; @used_as_key

overlap_basic_embed =  [
  ; @name identity
  tag: 0 //
  ; @name x
  tag: 1, hash: bytes .size 32
]

non_overlap_basic_embed = [
  ; @name first
  x: uint, tag: 0 //
  ; @name second
  y: text, tag: 1
]

non_overlap_basic_embed_multi_fields = [
  ; @name first
  x: uint, z: uint //
  ; @name second
  y: text, z: uint
]

non_overlap_basic_embed_mixed = [
  ; @name first
  x: uint, tag: 0 //
  ; @name second
  y: text, z: uint
]

bytes_uint = (bytes, uint)

non_overlap_basic_embed_mixed_explicit = [
  ; @name first
  x: uint, tag: 0 //
  ; @name second
  y: text, z: uint //
  ; @name third
  bytes_uint
]

basic = (uint, text)

basic_arr = [basic]

; not overlap since double array for second
non_overlap_basic_not_basic = [
  ; @name group
  basic //
  ; @name group_arr
  basic_arr //
  ; @name group_tagged
  #6.11(basic) //
  ; @name group_bytes
  bytes .cbor basic_arr
]

c_enum = 3 / 1 / 4

enums = [
	c_enum,
	type_choice,
]

plain = (d: #6.13(uint), e: tagged_text)

plain_arrays = [
    embedded: plain,
    single: [plain],
    multi: [*plain],
]

group_choice = [ 3 // #6.10(2) // foo // 0, x: uint // plain ]

foo_bytes = bytes .cbor foo

; since we don't generate code for definitions like the above (should we if no one refers to it?)
cbor_in_cbor = [foo_bytes, uint_bytes: bytes .cbor uint, tagged_foo_bytes]

tagged_foo_bytes = #6.20(bytes .cbor foo)

signed_ints = [
	u_8: uint .size 1,
	u_16: uint .size 2,
	u_32: uint .size 4,
	u_64: uint .size 8,
	i_8: int .size 1,
	i_16: int .size 2,
	i_32: int .size 4,
	i_64: int .size 8,
	n_64: nint
	u64_max: 18446744073709551615,
	; this test assumes i64::BITS == isize::BITS (i.e. 64-bit programs) or else the cddl parsing lib would mess up
	; if this test fails on your platform we might need to either remove this part
	; or make a fix for the cddl library.
	; The fix would be ideal as even though the true min in CBOR would be -u64::MAX
	; we can't test that since isize::BITS is never > 64 in any normal system and likely never will be
	i64_min: -9223372036854775808
]

default_uint = uint .default 1337

map_with_defaults = {
	? 1 : default_uint
	? 2 : text .default "two"
}

; TODO: preserve-encodings remembering optional fixed values. Issue: https://github.com/dcSpark/cddl-codegen/issues/205
array_opt_fields = [
;  ? x: null,
  ? a: uint,
  ? b: text,
	c: nint,
  ? d: text,
    y: #6.10(1),
  ? e: non_overlapping_type_choice_some
;  ? z: null,
]

hash = bytes .size (0..8)

bounds = [
    w: -1000 .. 1000
    x: uint .le 7,
    y: nint .ge -5,
    z: text .size (3..14),
    a: [* uint] .size (1..3),
    b: { * uint => uint } .le 3
]

bounds_type_choice = bytes .size (0..64)
                   / text .size (0..64)

bounds_group_choice = [
    ; @name a
    a: uint, b: text .le 4 //
    ; @name b
    hash //
    ; @name c
    1, x: hash, y: hash
]

overlapping_inlined = [
    ; @name one
    0 //
    ; @name two
    0, uint //
    ; @name three
    0, uint, text
]

enum_opt_embed_fields = [
    ; @name ea
    1 //
    ; @name eb
    1, ?text, 5 //
    ; @name ec
    1, uint, 7 //
; doesn't parse but would result in triple nesting so worth testing if we can ever parse it
;  1, ? (text / null), #6.9(9)
    ; @name ed
    1, uint, ?text //
    ; @name ee
    1, uint, ?bytes, uint //
    ;  @name ef
    1, ? non_overlapping_type_choice_some, #6.11(11) //
    ; @name eg
    1, ? overlapping_inlined, #6.13(13)
]

custom_bytes = bytes ; @custom_serialize custom_serialize_bytes @custom_deserialize custom_deserialize_bytes

struct_with_custom_serialization = [
  custom_bytes,
  field: bytes, ; @custom_serialize custom_serialize_bytes @custom_deserialize custom_deserialize_bytes
  overridden: custom_bytes, ; @custom_serialize write_hex_string @custom_deserialize read_hex_string
  tagged1: #6.9(custom_bytes),
  tagged2: #6.9(uint), ; @custom_serialize write_tagged_uint_str @custom_deserialize read_tagged_uint_str 
]
