#!/usr/bin/env bash
# Regenerates the crates under fuzz (fuzz/generated/, gitignored), their probe lists, and the seed
# corpora.
#
# Two crates, two targets:
#   - from_cbor_bytes            (fuzz/generated/rust)           — the preserve-encodings fixture,
#     the richest deserialization surface.
#   - from_cbor_bytes_recursive  (fuzz/generated/recursive/rust) — tests/corpus/recursive.cddl built
#     WITH --deserialize-depth-limit, so hostile-deep input fails gracefully
#     (DeserializeFailure::DepthLimitExceeded) instead of overflowing the stack (SIGABRT). The fuzz
#     process boundary is the only oracle that can see that abort, so this is the repo's
#     stack-overflow guard.
#
# Mirrors what integration_tests::preserve_encodings' run_test does for the preserve crate: generate
# with --preserve-encodings, then append the @custom_serialize fragments the fixture needs.
set -euo pipefail
cd "$(dirname "$0")/.."

# --- preserve-encodings crate -------------------------------------------------------------------
cargo run --release -- --input=tests/preserve-encodings/input.cddl --output=fuzz/generated \
    --preserve-encodings=true --wasm=false
printf '\nuse serialization::*;\n\n' >> fuzz/generated/rust/src/lib.rs
cat tests/custom_serialization_preserve >> fuzz/generated/rust/src/lib.rs

# --- recursive crate (with the depth guard) -----------------------------------------------------
# --preserve-encodings so the round-trip-fidelity oracle (accepted input must re-encode
# byte-identically) holds; --deserialize-depth-limit turns the recursive-descent deserializer's
# unbounded recursion into a graceful DepthLimitExceeded error.
cargo run --release -- --input=tests/corpus/recursive.cddl --output=fuzz/generated/recursive \
    --preserve-encodings=true --wasm=false --deserialize-depth-limit=64
# Both generated crates are emitted as the `cddl-lib` package; cargo refuses two packages of the
# same name in one workspace, so rename the recursive one (Cargo.toml re-maps it to `recursive_lib`).
sed -i 's/^name = "cddl-lib"$/name = "cddl-lib-recursive"/' fuzz/generated/recursive/rust/Cargo.toml

# --- derived probe lists ------------------------------------------------------------------------
# The set of types a target fuzzes is DERIVED from the generated crate's `impl Deserialize for <T>`
# set, not hand-synced — a new rule in the fuzzed spec lands in the probe set with zero manual edits,
# and drift becomes impossible rather than merely detected. Each list is written as a full `probe!`
# invocation the target `include!`s. A vacuity floor fails this script if the extraction regex rots
# and silently shrinks the set (mirroring the repo's vacuity-floor idiom).
#
# $1 = generated serialization.rs   $2 = crate path (rename target)   $3 = out .in file   $4 = floor
gen_probe_list() {
    {
        echo "// GENERATED by fuzz/generate.sh — do not edit. Derived from \`impl Deserialize for <T>\`."
        # A full \`fn\` item so the target can \`include!\` it in item position (the well-supported use
        # of include!, unlike expression position). The target defines \`probe!\` before the include
        # and calls \`probe_all(data)\` from its fuzz body.
        echo "fn probe_all(data: &[u8]) {"
        echo "    probe!("
        echo "        data,"
        grep -oE 'impl Deserialize for [A-Za-z_][A-Za-z0-9_]*' "$1" \
            | awk -v p="$2" '{ print "        " p "::" $NF "," }' | sort -u
        echo "    );"
        echo "}"
    } > "$3"
    local n
    n=$(grep -c '::' "$3")
    if [ "$n" -lt "$4" ]; then
        echo "ERROR: probe-list floor breach for $3: extracted $n types, floor is $4 — the extraction regex likely rotted against the generated crate." >&2
        exit 1
    fi
    echo "probe list $3: $n types (floor $4)"
}

gen_probe_list fuzz/generated/rust/src/serialization.rs \
    cddl_lib fuzz/generated/probe_list.in 20
gen_probe_list fuzz/generated/recursive/rust/src/serialization.rs \
    recursive_lib fuzz/generated/recursive_probe_list.in 1

# --- seed corpora -------------------------------------------------------------------------------
# from_cbor_bytes: every hand-derived RFC 8949 hex vector in ALL THREE golden-hex suites. The crate
# under fuzz is built with --preserve-encodings, so the preserve/canonical suites' irregular
# encodings (indefinite chunks, non-minimal heads) are exactly the inputs its decode paths exist for
# — seeding only the default suite left those paths unexercised by the corpus.
mkdir -p fuzz/corpus/from_cbor_bytes
python3 - <<'EOF'
import re, hashlib
for path in ('tests/golden_hex/tests.rs',
             'tests/golden_hex_preserve/tests.rs',
             'tests/golden_hex_canonical/tests.rs'):
    try:
        src = open(path).read()
    except FileNotFoundError:
        continue
    for a in re.findall(r'&\[((?:\s*0x[0-9a-fA-F]{2},?\s*)+)\]', src):
        data = bytes(int(b, 16) for b in re.findall(r'0x([0-9a-fA-F]{2})', a))
        if data:
            open(f'fuzz/corpus/from_cbor_bytes/{hashlib.sha1(data).hexdigest()[:16]}', 'wb').write(data)
EOF

# from_cbor_bytes_recursive: the hand-built hostile-deep vector from
# integration_tests::deserialize_depth_limit_guards_recursion (100_000 nested `array(2), uint 0,
# array(1)` frames terminated by an empty-children leaf — this is what SIGABRTs with the flag OFF),
# plus a few shallow valid `tree` values so the fuzzer has non-degenerate positive seeds.
mkdir -p fuzz/corpus/from_cbor_bytes_recursive
python3 - <<'EOF'
import os
d = 'fuzz/corpus/from_cbor_bytes_recursive'
# hostile-deep: must yield DepthLimitExceeded, never abort
hostile = b''.join(b'\x82\x00\x81' for _ in range(100_000)) + b'\x82\x00\x80'
open(os.path.join(d, 'hostile_deep'), 'wb').write(hostile)
# shallow valid trees (definite-length arrays): value + children
open(os.path.join(d, 'leaf'), 'wb').write(bytes([0x82, 0x00, 0x80]))               # tree(0, [])
open(os.path.join(d, 'one_child'), 'wb').write(bytes([0x82, 0x01, 0x81, 0x82, 0x02, 0x80]))  # tree(1,[tree(2,[])])
open(os.path.join(d, 'two_children'), 'wb').write(
    bytes([0x82, 0x03, 0x82, 0x82, 0x04, 0x80, 0x82, 0x05, 0x80]))                  # tree(3,[tree(4,[]),tree(5,[])])
EOF

echo "done — now:"
echo "  cd fuzz && cargo +nightly fuzz run from_cbor_bytes"
echo "  cd fuzz && cargo +nightly fuzz run from_cbor_bytes_recursive"
