// The wire is an array holder.  Every custom scalar is text (not bytes), every complete record or
// table owner is text (not its declared array/map), and both map routes contain custom text key and
// value legs.  Thus parsing and re-emitting the complete holder proves both codec directions stay
// routed at each placement; a silent fallback in either direction cannot reproduce these bytes.
#[cfg(test)]
mod custom_codec_coherence {
    use super::*;
    use serialization::Deserialize;

    fn bytes(hex: &str) -> Vec<u8> {
        hex.split_whitespace()
            .map(|part| u8::from_str_radix(part, 16).unwrap())
            .collect()
    }

    #[test]
    fn every_accepted_complete_pair_round_trips_its_non_default_wire_through_holder() {
        // holder[15]: 3 alias/field text values; two record-owner text values; eight table-owner
        // text values; a table with custom text key/value; and an open map with custom rest
        // text key/value beside its fixed uint key.
        let wire = bytes(
            "8f 61 61 61 62 61 63 62 61 72 62 6d 72 62 74 77 62 67 74 62 70 74 62 6e 74 62 62 74 62 72 74 62 6e 70 62 62 70 \
             a1 61 6b 61 76 a2 01 00 61 72 61 73",
        );
        let value = Holder::from_cbor_bytes(&wire).expect("the custom-reader holder wire parses");
        assert_eq!(
            coherence_bytes(&value),
            wire,
            "every complete custom pair must re-emit its deliberately non-default wire",
        );

        // Assert semantic values before re-parsing the emitted bytes. These are distinct markers,
        // so either custom direction reverting to the generated bytes/map/record codec fails here.
        assert_eq!(value.alias, b"a");
        assert_eq!(value.array_field, b"b");
        assert_eq!(value.map_field, b"c");
        assert_eq!(value.array_record.value, 1);
        assert_eq!(value.map_record.value, 1);
        assert_eq!(value.whole_table.get().get("w"), Some(&1));
        assert_eq!(value.generic_table.get().get("g"), Some(&1));
        assert_eq!(value.pair_table.get().len(), 1);
        assert_eq!(value.non_empty_table.get().get(&"n".to_owned()), Some(&1));
        assert_eq!(value.bounded_table.get().len(), 2);
        assert_eq!(value.reject_table.get().len(), 1);
        assert_eq!(value.non_empty_pair_table.get().len(), 1);
        assert_eq!(value.bounded_pair_table.get().len(), 2);
        assert_eq!(value.positions.get(b"k" as &[u8]), Some(&b"v".to_vec()));
        assert_eq!(value.open.rest.get(b"r" as &[u8]), Some(&b"s".to_vec()));

        let reparsed = Holder::from_cbor_bytes(&coherence_bytes(&value))
            .expect("the custom writer's output must feed the paired reader");
        assert_eq!(reparsed.alias, value.alias);
        assert_eq!(reparsed.array_field, value.array_field);
        assert_eq!(reparsed.map_field, value.map_field);
        assert_eq!(reparsed.array_record.value, value.array_record.value);
        assert_eq!(reparsed.map_record.value, value.map_record.value);
        assert_eq!(reparsed.whole_table.get(), value.whole_table.get());
        assert_eq!(reparsed.generic_table.get(), value.generic_table.get());
        assert_eq!(reparsed.pair_table.get(), value.pair_table.get());
        assert_eq!(reparsed.non_empty_table.get(), value.non_empty_table.get());
        assert_eq!(reparsed.bounded_table.get(), value.bounded_table.get());
        assert_eq!(reparsed.reject_table.get(), value.reject_table.get());
        assert_eq!(reparsed.non_empty_pair_table.get(), value.non_empty_pair_table.get());
        assert_eq!(reparsed.bounded_pair_table.get(), value.bounded_pair_table.get());
        assert_eq!(reparsed.positions, value.positions);
        assert_eq!(reparsed.open.rest, value.open.rest);
    }
}
