address = [
    bytes, ; @name address
    uint   ; @name checksum
]

protocol_param_update = {
    0:  uint, ; @name minfee_a
    1:  uint, ; @name minfee_b
}

block = [
    ; @name ebb_block_wrapper
    0, bytes ; @name ebb_block_cbor
    //
    ; @name main_block_wrapper
    1, bytes ; @name main_block_cbor
]

typechoice =
    [0, bytes] ; @name case_1
    /
    [1, bytes] ; @name case_2

protocol_magic = uint ; @newtype get

typechoice_variants =
    text      ; @name case_1
    /
    [* text]  ; @name case_2
