//! Declarative changeset model for the generated crates' `Cargo.toml` files.
//!
//! The three manifests (`rust/Cargo.toml`, `wasm/Cargo.toml`, `wasm/json-gen/Cargo.toml`) are no
//! longer whole-file writes. Each run the tool declares an ordered set of [`ManifestOp`]s over TOML
//! key paths and *applies* them ([`apply`]) to whatever manifest already exists on disk (or to an
//! empty document on first run). Keys no op mentions are never touched, so user-added dependencies,
//! `[profile]` sections, comments, blank lines, and formatting all survive regeneration
//! byte-for-byte (`toml_edit` preserves each node's decor). This is the same contract `cargo add` /
//! `cargo remove` make on user-owned manifests, and they use the same crate underneath.
//!
//! The three op kinds are the per-field collision rules:
//! * [`ManifestOp::Set`] — tool-owned key: written every run, overwriting whatever is there. User
//!   edits to these are overwritten by design (the dep set is version-coupled to the emitted code).
//! * [`ManifestOp::SeedOnce`] — written only if the key is absent (existence check only, never a
//!   content read), so it stays on the safe side of the determinism line. `package.version` is the
//!   one seeded key: the tool has no opinion on it after the initial `0.1.0`/`0.0.1`.
//! * [`ManifestOp::Remove`] — tombstone: a key the tool once managed and no longer wants, deleted if
//!   present (with empty parent tables garbage-collected). Tombstones are kept forever (one line
//!   each) so a manifest generated by any old tool version converges on regeneration.
//!
//! **The unconditional ops come from an append-only change LOG**, one per manifest
//! (`static/manifest_changes/{rust,wasm,json_gen}.toml`) — the single source of truth. Each log is
//! an ordered list of entries, each an `id` + dotted `path` + exactly one of `set` / `seed` /
//! `remove`. [`fold_log`] folds them per-path last-write-wins (final `set` → [`ManifestOp::Set`],
//! final `seed` → [`ManifestOp::SeedOnce`], final `remove` → [`ManifestOp::Remove`], i.e. a dropped
//! key is auto-tombstoned) and emits the folded ops in first-mention order of each path. Editing is
//! append-only: to change a key you append another entry, to drop one you append a `remove` — so the
//! log records the full history and a key the tool ever managed can never be silently unmentioned
//! (the property the old separate ledger enforced is now structural). Contiguous ids, and one-of
//! per entry, are hard errors naming the log file. The `static/Cargo_{rust,wasm,json_gen}.toml`
//! files are *derived* from the log ([`render_derived_template`]) as a human-readable snapshot of
//! the current live keys — generated, never read at runtime, kept in sync by a drift gate.
//!
//! Flag/type-conditional deps emit **set-or-remove, never set-or-skip**: e.g. `--preserve-encodings`
//! false emits `Remove(dependencies.linked-hash-map)`, so flipping a flag off doesn't strand a stale
//! dep. An unparseable existing manifest is a hard error naming the file — never a silent clobber,
//! since a parse failure is exactly the case where the user has content we can't safely preserve.

use crate::cli::Cli;
use crate::intermediate::{ConceptualRustType, IntermediateTypes, Primitive, RustStructType};
use toml_edit::{DocumentMut, Entry, Item, Table};

/// A dotted key path into a TOML document, e.g. `["dependencies", "cbor_event"]`.
pub type KeyPath = Vec<String>;

/// One declarative operation over a TOML key path. See the module docs for the collision contract.
#[derive(Debug, Clone)]
pub enum ManifestOp {
    /// Tool-owned key: written every run, overwriting whatever value is there.
    Set(Item),
    /// Written only if the key is absent (existence check only — never reads the existing value).
    SeedOnce(Item),
    /// Tombstone: delete the key if present, then garbage-collect any now-empty parent tables.
    Remove,
}

/// Error applying a changeset — currently only an unparseable existing manifest. Carries the file
/// name so the caller doesn't have to re-attach it.
#[derive(Debug)]
pub struct ManifestError {
    pub file: String,
    pub message: String,
}

impl std::fmt::Display for ManifestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.file, self.message)
    }
}

impl std::error::Error for ManifestError {}

/// Apply `ops` in order to `existing` (parsed if `Some`, else a fresh empty document) and serialize
/// the result. Pure: no disk I/O, output is a function of `(ops, existing)` only. `file_name` is
/// used solely for diagnostics (naming the file in a parse error).
pub fn apply(
    ops: &[(KeyPath, ManifestOp)],
    existing: Option<&str>,
    file_name: &str,
) -> Result<String, ManifestError> {
    let mut doc = match existing {
        Some(text) => text.parse::<DocumentMut>().map_err(|e| ManifestError {
            file: file_name.to_owned(),
            message: format!("existing manifest is not valid TOML: {e}"),
        })?,
        None => DocumentMut::new(),
    };
    for (path, op) in ops {
        match op {
            ManifestOp::Set(item) => set_leaf(&mut doc, path, item.clone()),
            ManifestOp::SeedOnce(item) => {
                if item_at(doc.as_table(), path).is_none() {
                    set_leaf(&mut doc, path, item.clone());
                }
            }
            ManifestOp::Remove => remove_leaf(doc.as_table_mut(), path),
        }
    }
    Ok(doc.to_string())
}

/// Descend to (creating as needed) the table addressed by `segments`, borrowing cargo's heuristic of
/// marking auto-created intermediate tables implicit so an empty parent header is never printed.
/// Recursive (not a reassigning loop) to satisfy the borrow checker on the walked `&mut`.
fn table_at<'a>(table: &'a mut Table, segments: &[String]) -> &'a mut Table {
    match segments.split_first() {
        None => table,
        Some((seg, rest)) => {
            let item = table.entry(seg).or_insert_with(|| {
                let mut t = Table::new();
                t.set_implicit(true);
                Item::Table(t)
            });
            // A tool-owned path colliding with a user's scalar of the same name is a genuine
            // conflict; overwrite it with a table (the tool owns these paths).
            if item.as_table_mut().is_none() {
                let mut t = Table::new();
                t.set_implicit(true);
                *item = Item::Table(t);
            }
            table_at(item.as_table_mut().unwrap(), rest)
        }
    }
}

/// Set the leaf key at `path`. On overwrite, transfer the existing value's decor onto the new value
/// (cargo's pattern) so an inline `# comment` on a bumped dep survives; the `Entry::Occupied` reuse
/// of the existing key also preserves a full-line comment written above the key.
fn set_leaf(doc: &mut DocumentMut, path: &[String], item: Item) {
    let Some((leaf, parents)) = path.split_last() else {
        return;
    };
    let table = table_at(doc.as_table_mut(), parents);
    match table.entry(leaf) {
        Entry::Occupied(mut e) => {
            let old_decor = e.get().as_value().map(|v| v.decor().clone());
            let slot = e.get_mut();
            *slot = item;
            if let (Some(decor), Some(v)) = (old_decor, slot.as_value_mut()) {
                *v.decor_mut() = decor;
            }
        }
        Entry::Vacant(e) => {
            e.insert(item);
        }
    }
}

/// Fetch the item at `path`, if present (used for `SeedOnce`'s existence check). Walks header and
/// inline tables alike.
fn item_at<'a>(table: &'a Table, path: &[String]) -> Option<&'a Item> {
    let (first, rest) = path.split_first()?;
    let mut item = table.get(first)?;
    for seg in rest {
        item = item.as_table_like()?.get(seg)?;
    }
    Some(item)
}

/// Remove the leaf at `path` if present, then garbage-collect emptied parent tables on the way back
/// up — so tombstoning the last dep in a table we created also drops the now-empty `[table]` header,
/// while a table still holding user keys is left alone.
fn remove_leaf(table: &mut Table, path: &[String]) {
    let Some((seg, rest)) = path.split_first() else {
        return;
    };
    if rest.is_empty() {
        table.remove(seg);
        return;
    }
    if let Some(child) = table.get_mut(seg).and_then(Item::as_table_mut) {
        remove_leaf(child, rest);
        if child.is_empty() {
            table.remove(seg);
        }
    }
}

// ---- op builders ----------------------------------------------------------------------------

/// Parse a TOML value snippet (e.g. `"0.4.3"` or `{ version = "1.0" }`) into an [`Item`], returning
/// a message on failure. Snippets in the change logs are user-editable, so this is the fallible form.
fn try_val(snippet: &str) -> Result<Item, String> {
    let doc = format!("x = {snippet}")
        .parse::<DocumentMut>()
        .map_err(|e| e.to_string())?;
    doc.get("x")
        .cloned()
        .ok_or_else(|| "value snippet produced no value".to_owned())
}

/// Infallible [`try_val`] for in-code op builders whose snippets are compile-time constants.
fn val(snippet: &str) -> Item {
    try_val(snippet).expect("op-builder value snippet is valid TOML")
}

fn key_path(segments: &[&str]) -> KeyPath {
    segments.iter().map(|s| (*s).to_owned()).collect()
}

/// A `[dependencies]` entry emitted set-or-remove: `Set(spec)` when `enabled`, else `Remove`.
fn dep(name: &str, spec: &str, enabled: bool) -> (KeyPath, ManifestOp) {
    let path = key_path(&["dependencies", name]);
    let op = if enabled {
        ManifestOp::Set(val(spec))
    } else {
        ManifestOp::Remove
    };
    (path, op)
}

/// The write-only version stamp: `package.metadata.cddl-codegen.generated-with = <tool version>`.
/// The tool NEVER reads this back — reading would make output depend on prior disk contents.
fn version_stamp() -> (KeyPath, ManifestOp) {
    (
        key_path(&["package", "metadata", "cddl-codegen", "generated-with"]),
        ManifestOp::Set(val(&format!("\"{}\"", env!("CARGO_PKG_VERSION")))),
    )
}

/// The folded outcome of all log entries for one key path (last write wins). Held internally while
/// folding so the last `set`/`seed`/`remove` seen for a path is the one that becomes its op.
enum FoldedAction {
    Set(Item),
    Seed(Item),
    Remove,
}

/// Read an append-only change log (already lib-name-substituted) and fold it into ordered ops. Each
/// `[[change]]` has an `id` (must be contiguous from 1), a dotted `path`, and EXACTLY ONE of
/// `set = "<snippet>"` / `seed = "<snippet>"` / `remove = true`. Entries fold per-path last-write-wins;
/// the emitted ops are in first-mention order of each path (deterministic). `file_name` names the log
/// in any error. A gap in ids, a missing/duplicated action, or an unparseable snippet is a hard error.
fn fold_log(raw: &str, file_name: &str) -> Result<Vec<(KeyPath, ManifestOp)>, ManifestError> {
    let err = |message: String| ManifestError {
        file: file_name.to_owned(),
        message,
    };
    let doc = raw
        .parse::<DocumentMut>()
        .map_err(|e| err(format!("change log is not valid TOML: {e}")))?;
    let Some(changes) = doc.get("change").and_then(Item::as_array_of_tables) else {
        return Ok(Vec::new());
    };

    // Fold in a Vec keyed by path: first mention appends (preserving order), later mentions of the
    // same path overwrite the action in place (last-write-wins). No map — order matters and the log
    // is tiny — so the whole thing stays a deterministic linear scan.
    let mut folded: Vec<(KeyPath, FoldedAction)> = Vec::new();
    for (i, entry) in changes.iter().enumerate() {
        let position = i + 1;
        let id = entry
            .get("id")
            .and_then(Item::as_integer)
            .ok_or_else(|| err(format!("change #{position} is missing an integer `id`")))?;
        if id != position as i64 {
            return Err(err(format!(
                "ids must be contiguous from 1: expected {position} at position {position}, found {id}"
            )));
        }
        let path_str = entry
            .get("path")
            .and_then(Item::as_str)
            .ok_or_else(|| err(format!("change id {id} is missing a string `path`")))?;
        let path: KeyPath = path_str.split('.').map(str::to_owned).collect();

        let snippet_val = |key: &str| -> Result<Item, ManifestError> {
            let snippet = entry.get(key).and_then(Item::as_str).ok_or_else(|| {
                err(format!(
                    "change id {id} `{key}` must be a TOML value snippet string"
                ))
            })?;
            try_val(snippet).map_err(|e| {
                err(format!(
                    "change id {id} `{key}` value `{snippet}` is not a valid TOML value: {e}"
                ))
            })
        };
        let action = match (
            entry.contains_key("set"),
            entry.contains_key("seed"),
            entry.contains_key("remove"),
        ) {
            (true, false, false) => FoldedAction::Set(snippet_val("set")?),
            (false, true, false) => FoldedAction::Seed(snippet_val("seed")?),
            (false, false, true) => {
                if entry.get("remove").and_then(Item::as_bool) != Some(true) {
                    return Err(err(format!("change id {id} `remove` must be `true`")));
                }
                FoldedAction::Remove
            }
            _ => {
                return Err(err(format!(
                    "change id {id} must have EXACTLY ONE of `set`, `seed`, `remove`"
                )));
            }
        };
        match folded.iter_mut().find(|(p, _)| *p == path) {
            Some(slot) => slot.1 = action,
            None => folded.push((path, action)),
        }
    }

    Ok(folded
        .into_iter()
        .map(|(path, action)| {
            let op = match action {
                FoldedAction::Set(item) => ManifestOp::Set(item),
                FoldedAction::Seed(item) => ManifestOp::SeedOnce(item),
                FoldedAction::Remove => ManifestOp::Remove,
            };
            (path, op)
        })
        .collect())
}

/// Read `<static_dir>/<log_name>`, apply the `cddl-lib` → `--lib-name` substitution (the same
/// substring replacement the whole log text goes through, so `dependencies.cddl-lib` and the package
/// name track the flag), and fold it into ops. The substitution runs on the raw text before parsing.
fn ops_from_log(cli: &Cli, log_name: &str) -> std::io::Result<Vec<(KeyPath, ManifestOp)>> {
    let raw =
        std::fs::read_to_string(cli.static_dir.join(log_name))?.replace("cddl-lib", &cli.lib_name);
    fold_log(&raw, log_name)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
}

/// The do-not-edit header prepended to a derived template, pointing at its source log.
// dead_code: the only bin-target consumer is the #[cfg(test)] template drift gate.
#[cfg_attr(not(test), allow(dead_code))]
fn derived_header(log_name: &str) -> String {
    format!(
        "# @generated by cddl-codegen — DO NOT EDIT.\n\
         # Source of truth: static/{log_name} (append-only change log; edit that, never this file).\n\
         # Regenerate: BLESS_MANIFEST_TEMPLATES=1 cargo test manifest_template_drift\n\
         # See static/manifest_changes/README.md for the log format and editing rules.\n\n"
    )
}

/// Render the human-readable derived template for a change log: the fold's live keys applied to an
/// empty document (unconditional current state only — no conditional deps, no version stamp), under
/// the default `cddl-lib` naming, prefixed with the do-not-edit header. This is the SAME fold+apply
/// used at runtime, so the committed template can't drift from the log's meaning. `raw_log` is the
/// unsubstituted log text; `log_name`/`template_name` name the source and output for diagnostics.
// dead_code: the only bin-target consumer is the #[cfg(test)] template drift gate.
#[cfg_attr(not(test), allow(dead_code))]
pub fn render_derived_template(
    raw_log: &str,
    log_name: &str,
    template_name: &str,
) -> Result<String, ManifestError> {
    let ops = fold_log(raw_log, log_name)?;
    let body = apply(&ops, None, template_name)?;
    Ok(format!("{}{body}", derived_header(log_name)))
}

/// The declarative changeset for `rust/Cargo.toml`: change-log keys + flag/type-conditional deps
/// (set-or-remove) + the write-only version stamp. Absorbs the conditional dep logic that used to
/// string-push into the template.
pub fn ops_for_rust(
    types: &IntermediateTypes,
    export_raw_bytes_encoding_trait: bool,
    cli: &Cli,
) -> std::io::Result<Vec<(KeyPath, ManifestOp)>> {
    let mut ops = ops_from_log(cli, "manifest_changes/rust.toml")?;

    // flag-conditional deps
    ops.push(dep("linked-hash-map", "\"0.5.3\"", cli.preserve_encodings));
    ops.push(dep("derivative", "\"2.2.0\"", cli.preserve_encodings));
    ops.push(dep(
        "serde",
        "{ version = \"1.0\", features = [\"derive\"] }",
        cli.json_serde_derives,
    ));
    ops.push(dep("serde_json", "\"1.0.57\"", cli.json_serde_derives));
    ops.push(dep("schemars", "\"1.2.1\"", cli.json_schema_export));

    // type-conditional deps (mirrors the old `rust_cargo_toml` conditions exactly)
    let needs_hex = export_raw_bytes_encoding_trait
        || types
            .rust_structs()
            .iter()
            .any(|(_, rust_struct)| match rust_struct.variant() {
                RustStructType::Wrapper { wrapped, .. } => {
                    !rust_struct.config().custom_json
                        && matches!(
                            wrapped.resolve_alias_shallow(),
                            ConceptualRustType::Primitive(Primitive::Bytes)
                        )
                }
                _ => false,
            });
    ops.push(dep("hex", "\"0.4.3\"", needs_hex));

    let needs_wasm_bindgen = cli.wasm
        && types
            .rust_structs()
            .values()
            .any(|rust_struct| matches!(rust_struct.variant(), RustStructType::CStyleEnum { .. }));
    ops.push(dep("wasm-bindgen", "\"0.2\"", needs_wasm_bindgen));

    ops.push(version_stamp());
    Ok(ops)
}

/// The declarative changeset for `wasm/Cargo.toml`. The `cddl-lib` path-dep key name (and the
/// package name) derive from `--lib-name` via the same substring replacement as before.
pub fn ops_for_wasm(cli: &Cli) -> std::io::Result<Vec<(KeyPath, ManifestOp)>> {
    let mut ops = ops_from_log(cli, "manifest_changes/wasm.toml")?;
    ops.push(dep("serde", "\"1.0\"", cli.json_serde_derives));
    ops.push(dep("serde_json", "\"1.0.57\"", cli.json_serde_derives));
    ops.push(dep(
        "serde-wasm-bindgen",
        "\"0.6.5\"",
        cli.json_serde_derives,
    ));
    ops.push(version_stamp());
    Ok(ops)
}

/// The declarative changeset for `wasm/json-gen/Cargo.toml` (no conditional deps of its own).
pub fn ops_for_json_gen(cli: &Cli) -> std::io::Result<Vec<(KeyPath, ManifestOp)>> {
    let mut ops = ops_from_log(cli, "manifest_changes/json_gen.toml")?;
    ops.push(version_stamp());
    Ok(ops)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set(path: &[&str], v: &str) -> (KeyPath, ManifestOp) {
        (key_path(path), ManifestOp::Set(val(v)))
    }
    fn seed(path: &[&str], v: &str) -> (KeyPath, ManifestOp) {
        (key_path(path), ManifestOp::SeedOnce(val(v)))
    }
    fn remove(path: &[&str]) -> (KeyPath, ManifestOp) {
        (key_path(path), ManifestOp::Remove)
    }

    /// A representative rust-ish changeset built by hand (no template/disk needed).
    fn sample_ops() -> Vec<(KeyPath, ManifestOp)> {
        vec![
            set(&["package", "name"], "\"my-lib\""),
            seed(&["package", "version"], "\"0.1.0\""),
            set(&["package", "edition"], "\"2024\""),
            set(&["dependencies", "cbor_event"], "\"2.4.0\""),
        ]
    }

    #[test]
    fn fresh_produces_full_manifest() {
        let out = apply(&sample_ops(), None, "rust/Cargo.toml").unwrap();
        assert!(out.contains("name = \"my-lib\""));
        assert!(out.contains("version = \"0.1.0\""));
        assert!(out.contains("edition = \"2024\""));
        assert!(out.contains("cbor_event = \"2.4.0\""));
        // parses back as valid TOML
        out.parse::<DocumentMut>().unwrap();
    }

    #[test]
    fn rerun_is_byte_identical() {
        let ops = sample_ops();
        let first = apply(&ops, None, "rust/Cargo.toml").unwrap();
        let second = apply(&ops, Some(&first), "rust/Cargo.toml").unwrap();
        assert_eq!(
            first, second,
            "applying ops onto our own output must be a fixed point"
        );
    }

    #[test]
    fn untouched_user_content_survives_including_overwritten_key_decor() {
        let existing = "\
[package]
name = \"my-lib\"
version = \"0.1.0\"

# release tuning the user added
[profile.release]
lto = true

[dependencies]
# keep cbor_event pinned deliberately
cbor_event = \"1.0.0\" # inline note
anyhow = \"1\" # a dep the tool has no opinion on
";
        // The tool bumps cbor_event; everything else is untouched.
        let ops = vec![set(&["dependencies", "cbor_event"], "\"2.4.0\"")];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        // user's profile section + extra dep survive
        assert!(out.contains("[profile.release]"));
        assert!(out.contains("lto = true"));
        assert!(out.contains("anyhow = \"1\""));
        // comments adjacent to the overwritten key survive (decor transfer)
        assert!(out.contains("# keep cbor_event pinned deliberately"));
        assert!(out.contains("# inline note"));
        // value was actually overwritten
        assert!(out.contains("cbor_event = \"2.4.0\""));
        assert!(!out.contains("1.0.0"));
    }

    #[test]
    fn tombstone_removes_key_and_gcs_empty_parent() {
        let existing = "\
[package]
name = \"my-lib\"

[dependencies]
old-only-dep = \"0.1\"
";
        let ops = vec![remove(&["dependencies", "old-only-dep"])];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        assert!(!out.contains("old-only-dep"));
        // the table had no other keys, so the now-empty [dependencies] header is GC'd
        assert!(
            !out.contains("[dependencies]"),
            "empty parent table must be removed:\n{out}"
        );
    }

    #[test]
    fn tombstone_keeps_parent_with_other_keys() {
        let existing = "\
[dependencies]
old-only-dep = \"0.1\"
anyhow = \"1\"
";
        let ops = vec![remove(&["dependencies", "old-only-dep"])];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        assert!(!out.contains("old-only-dep"));
        assert!(out.contains("[dependencies]"));
        assert!(out.contains("anyhow = \"1\""));
    }

    #[test]
    fn flag_flip_removes_stale_dep() {
        // manifest previously generated with --preserve-encodings
        let existing = "\
[dependencies]
cbor_event = \"2.4.0\"
linked-hash-map = \"0.5.3\"
derivative = \"2.2.0\"
";
        // now regenerated WITHOUT the flag: those deps become Remove ops
        let ops = vec![
            dep("linked-hash-map", "\"0.5.3\"", false),
            dep("derivative", "\"2.2.0\"", false),
        ];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        assert!(!out.contains("linked-hash-map"));
        assert!(!out.contains("derivative"));
        assert!(out.contains("cbor_event = \"2.4.0\""));
    }

    #[test]
    fn seed_once_respects_existing_and_seeds_when_absent() {
        // present: user's version is preserved (existence check only)
        let existing = "\
[package]
name = \"my-lib\"
version = \"3.2.1\"
";
        let ops = vec![seed(&["package", "version"], "\"0.1.0\"")];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        assert!(out.contains("version = \"3.2.1\""));
        assert!(!out.contains("0.1.0"));

        // absent: the seed value is written
        let absent = "[package]\nname = \"my-lib\"\n";
        let out = apply(&ops, Some(absent), "rust/Cargo.toml").unwrap();
        assert!(out.contains("version = \"0.1.0\""));
    }

    #[test]
    fn set_overwrites_user_edited_tool_owned_key() {
        // the documented contract: a user edit to a tool-owned dep version is overwritten
        let existing = "[dependencies]\ncbor_event = \"9.9.9\"\n";
        let ops = vec![set(&["dependencies", "cbor_event"], "\"2.4.0\"")];
        let out = apply(&ops, Some(existing), "rust/Cargo.toml").unwrap();
        assert!(out.contains("cbor_event = \"2.4.0\""));
        assert!(!out.contains("9.9.9"));
    }

    #[test]
    fn malformed_existing_manifest_is_an_error_naming_the_file() {
        let err = apply(
            &sample_ops(),
            Some("this is [[[ not valid toml"),
            "wasm/Cargo.toml",
        )
        .unwrap_err();
        assert_eq!(err.file, "wasm/Cargo.toml");
        assert!(
            err.to_string().contains("wasm/Cargo.toml"),
            "error display must name the file: {err}"
        );
    }

    // ---- change-log reader ------------------------------------------------------------------

    /// Assemble a change log from `(path, action)` pairs, numbering ids contiguously from 1.
    fn log(entries: &[(&str, &str)]) -> String {
        let mut s = String::new();
        for (i, (path, action)) in entries.iter().enumerate() {
            s.push_str(&format!(
                "[[change]]\nid = {}\npath = \"{path}\"\n{action}\n\n",
                i + 1
            ));
        }
        s
    }

    /// Assert the op at `path` matches a predicate, panicking with context otherwise.
    fn op_at<'a>(ops: &'a [(KeyPath, ManifestOp)], path: &[&str]) -> Option<&'a ManifestOp> {
        ops.iter()
            .find(|(p, _)| p.iter().map(String::as_str).eq(path.iter().copied()))
            .map(|(_, op)| op)
    }

    #[test]
    fn fold_seed_and_set_become_their_ops_in_first_mention_order() {
        let raw = log(&[
            ("package.name", "set = '\"my-lib\"'"),
            ("package.version", "seed = '\"0.1.0\"'"),
            ("dependencies.cbor_event", "set = '\"2.4.0\"'"),
        ]);
        let ops = fold_log(&raw, "log.toml").unwrap();
        let paths: Vec<String> = ops.iter().map(|(p, _)| p.join(".")).collect();
        assert_eq!(
            paths,
            ["package.name", "package.version", "dependencies.cbor_event"]
        );
        assert!(matches!(
            op_at(&ops, &["package", "version"]),
            Some(ManifestOp::SeedOnce(_))
        ));
        assert!(matches!(
            op_at(&ops, &["package", "name"]),
            Some(ManifestOp::Set(_))
        ));
    }

    #[test]
    fn fold_set_then_set_keeps_last_value_at_first_position() {
        let raw = log(&[
            ("dependencies.cbor_event", "set = '\"2.0.0\"'"),
            ("package.name", "set = '\"my-lib\"'"),
            ("dependencies.cbor_event", "set = '\"2.4.0\"'"),
        ]);
        let ops = fold_log(&raw, "log.toml").unwrap();
        // first-mention order preserved: cbor_event stays first despite the later re-set
        assert_eq!(ops[0].0.join("."), "dependencies.cbor_event");
        let out = apply(&ops, None, "Cargo.toml").unwrap();
        assert!(
            out.contains("cbor_event = \"2.4.0\""),
            "last write wins:\n{out}"
        );
        assert!(!out.contains("2.0.0"));
    }

    #[test]
    fn fold_set_then_remove_emits_remove() {
        let raw = log(&[
            ("dependencies.old", "set = '\"0.1\"'"),
            ("dependencies.old", "remove = true"),
        ]);
        let ops = fold_log(&raw, "log.toml").unwrap();
        assert!(matches!(
            op_at(&ops, &["dependencies", "old"]),
            Some(ManifestOp::Remove)
        ));
    }

    #[test]
    fn fold_remove_then_set_emits_set() {
        let raw = log(&[
            ("dependencies.dep", "remove = true"),
            ("dependencies.dep", "set = '\"1.0\"'"),
        ]);
        let ops = fold_log(&raw, "log.toml").unwrap();
        assert!(matches!(
            op_at(&ops, &["dependencies", "dep"]),
            Some(ManifestOp::Set(_))
        ));
    }

    #[test]
    fn fold_gapped_ids_error_names_the_file() {
        let raw = "\
[[change]]
id = 1
path = \"package.name\"
set = '\"my-lib\"'

[[change]]
id = 3
path = \"package.edition\"
set = '\"2024\"'
";
        let err = fold_log(raw, "manifest_changes/rust.toml").unwrap_err();
        assert_eq!(err.file, "manifest_changes/rust.toml");
        assert!(
            err.to_string().contains("contiguous")
                && err.to_string().contains("manifest_changes/rust.toml"),
            "gapped-id error must name the file and mention contiguity: {err}"
        );
    }

    #[test]
    fn fold_entry_with_set_and_remove_is_an_error() {
        let raw = "\
[[change]]
id = 1
path = \"dependencies.dep\"
set = '\"1.0\"'
remove = true
";
        let err = fold_log(raw, "log.toml").unwrap_err();
        assert!(
            err.to_string().contains("EXACTLY ONE"),
            "both set+remove must be rejected: {err}"
        );
    }

    #[test]
    fn fold_entry_with_no_action_is_an_error() {
        let raw = "\
[[change]]
id = 1
path = \"dependencies.dep\"
";
        let err = fold_log(raw, "log.toml").unwrap_err();
        assert!(
            err.to_string().contains("EXACTLY ONE"),
            "an actionless entry must be rejected: {err}"
        );
    }

    #[test]
    fn fold_unparseable_snippet_is_an_error() {
        let raw = "\
[[change]]
id = 1
path = \"dependencies.dep\"
set = 'not = valid = toml'
";
        let err = fold_log(raw, "log.toml").unwrap_err();
        assert!(
            err.to_string().contains("not a valid TOML value"),
            "a bad value snippet must be rejected: {err}"
        );
    }

    #[test]
    fn derived_template_has_header_and_live_keys_only() {
        // a remove'd key must NOT appear in the derived template (applied to an empty doc = no-op)
        let raw = log(&[
            ("package.name", "set = '\"my-lib\"'"),
            ("dependencies.gone", "set = '\"1.0\"'"),
            ("dependencies.gone", "remove = true"),
        ]);
        let out =
            render_derived_template(&raw, "manifest_changes/rust.toml", "Cargo_rust.toml").unwrap();
        assert!(out.starts_with("# @generated by cddl-codegen"), "{out}");
        assert!(out.contains("static/manifest_changes/rust.toml"));
        assert!(out.contains("name = \"my-lib\""));
        assert!(
            !out.contains("gone"),
            "tombstoned key must be absent:\n{out}"
        );
    }
}
